import json
from datetime import datetime

def generate_threat_markdown_advisory(item: dict, analysis: dict) -> str:
    """Generates an executive-ready Markdown security advisory document."""
    title = item.get("title", "Security Threat Advisory")
    source = item.get("source", "Threat Intelligence Ingestion Hub")
    pub_date = item.get("pubDate", datetime.utcnow().isoformat() + "Z")
    cve_id = analysis.get("cveId", "N/A")
    cvss_score = analysis.get("cvssScore", 0.0)
    cvss_sev = analysis.get("cvssSeverity", "UNKNOWN")
    cwe_id = analysis.get("cweId", "N/A")
    cwe_name = analysis.get("cweName", "General Flaw")
    cisa_kev = analysis.get("cisaKevStatus", "NO_KNOWN_EXPLOITATION")
    mitre = analysis.get("mitreTtp", {})
    severity = analysis.get("severity", "MEDIUM")
    affected = analysis.get("affectedSystems", "Enterprise Infrastructure")
    reasoning = analysis.get("severityReasoning", "N/A")
    summary = analysis.get("executiveSummary", item.get("description", "No summary provided."))
    compliance = analysis.get("complianceImpact", [])
    action_plan = analysis.get("actionPlan", [])
    link = item.get("link", "#")

    md = f"""# SECURITY ADVISORY // {severity.upper()} PRIORITY
**Date:** {pub_date}  
**Source:** {source}  
**Reference Link:** [{title}]({link})  

---

## 1. Executive Summary
{summary}

---

## 2. Threat & Vulnerability Intelligence Metrics
| Metric | Value |
| :--- | :--- |
| **Identified CVE** | `{cve_id}` |
| **NIST NVD CVSS v3.1** | **{cvss_score} / 10.0** ({cvss_sev}) |
| **Weakness Classification** | `{cwe_id}`: {cwe_name} |
| **CISA KEV Status** | `{'🚨 CONFIRMED EXPLOITED IN WILD' if cisa_kev == 'CONFIRMED_EXPLOITED' else '🛡️ NO KNOWN ACTIVE EXPLOITATION'}` |
| **MITRE ATT&CK** | `{mitre.get('id', 'T1190')}` - {mitre.get('name', 'Exploit Public-Facing Application')} (Tactic: {mitre.get('tactic', 'Initial Access')}) |
| **Target Organization Asset** | {affected} |
| **Contextual Priority** | **{severity}** |

### Contextual Priority Rationale
> {reasoning}

---

## 3. Regulatory Compliance Framework Impact
{', '.join([f'`{c}`' for c in compliance]) if compliance else 'No direct compliance violations noted.'}

---

## 4. Engineering Remediation Action Plan
"""
    for idx, step in enumerate(action_plan, 1):
        md += f"{idx}. {step}\n"

    md += """
---
*Generated by SECURITYHELPDESK Autonomous Threat Intelligence Engine.*
"""
    return md.strip()

def generate_phishing_markdown_report(scraped: dict, analysis: dict) -> str:
    """Generates a Markdown Phishing Sandbox Audit Report."""
    url = scraped.get("url", "")
    domain = scraped.get("domain", "")
    is_https = scraped.get("isHttps", False)
    age_days = scraped.get("domainInfo", {}).get("ageDays")
    prob = analysis.get("phishingProbability", 0)
    level = analysis.get("dangerLevel", "UNKNOWN")
    reasoning = analysis.get("verdictReasoning", "")
    factors = analysis.get("riskFactors", [])
    layout = analysis.get("visualLayoutCheck", "")

    md = f"""# URL PHISHING AUDIT REPORT // {level.upper()}
**Target URL:** `{url}`  
**Domain:** `{domain}`  
**Audited At:** {datetime.utcnow().isoformat()}Z  

---

## 1. Verdict & Risk Gauge
* **Phishing Probability Score:** **{prob}%**
* **Danger Classification:** **{level}**
* **SSL Status:** `{'HTTPS Encrypted' if is_https else 'Insecure HTTP'}`
* **Domain Registration Age:** `{age_days if age_days is not None else 'Unknown'} days`

---

## 2. Identified Threat Factors
"""
    for f in factors:
        md += f"- ⚠️ {f}\n"

    md += f"""
---

## 3. HTML Structural & Layout Analysis
{layout}

---

## 4. Security Sandbox Justification
> {reasoning}

---
*Generated by SECURITYHELPDESK Phishing Sandbox Heuristics Engine.*
"""
    return md.strip()

def generate_scam_markdown_report(scraped: dict, analysis: dict) -> str:
    """Generates a Markdown Scam Detector Report."""
    domain = scraped.get("domain", "")
    scam_prob = analysis.get("scamProbability", 0)
    trust_score = analysis.get("trustScore", 100)
    red_flags = analysis.get("redFlags", [])
    signals = analysis.get("riskSignalsText", "")
    assessment = analysis.get("assessmentText", "")
    registrar = scraped.get("domainInfo", {}).get("registrar", "Unknown")
    age = scraped.get("domainInfo", {}).get("ageDays", "Unknown")

    md = f"""# WEBSITE SCAM & TRUST AUDIT REPORT
**Domain:** `{domain}`  
**Registrar:** `{registrar}`  
**Domain Age:** `{age} days`  
**Audited At:** {datetime.utcnow().isoformat()}Z  

---

## 1. Commercial Trust Assessment
* **Trust Score:** **{trust_score} / 100**
* **Scam Probability:** **{scam_prob}%**
* **Summary Assessment:** {assessment}

---

## 2. Identified Red Flags & Commercial Warnings
"""
    for flag in red_flags:
        md += f"- 🚩 {flag}\n"

    md += f"""
---

## 3. Policy & Contact Transparency Signals
{signals}

---
*Generated by SECURITYHELPDESK Commercial Website Auditor.*
"""
    return md.strip()
